// <auto-generated />
using KronikiPodwalaV2.DataObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KronikiPodwalaV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KronikiPodwalaV2.Models.EventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("eventModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDescription = "ABC",
                            EventName = "Walentynki"
                        },
                        new
                        {
                            Id = 2,
                            EventDescription = "ABC",
                            EventName = "Walentynki"
                        },
                        new
                        {
                            Id = 3,
                            EventDescription = "ABC",
                            EventName = "Walentynki"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
